server:
    servlet:
        context-path: /poc
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: none
it:
    example:
        phrase: test


logging:
    level:
        org:
            hibernate:
                SQL: INFO
                type: INFO